### ISSUE TITLE
Typo  "mil" is "mli" problem.

### ISSUE THREAD

**Issue by rangerdude** [rikgale/LocalAircraft#124]
This took me a bit tracking back to where the file was getting updated.

Here is the are in LocalAircraft..

0D0942,mli,# C501 3933

under [Mexico]
Last line of it. 

Just needs a little love to correct the typo  MLI. not MIL...

Thanks guys for what u do.

**Comment by rikgale** [comment]
Thanks for spotting the typo. 
All updated now.
